// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOMWZU0RKoLrYcOxgDHpnBQ5qSfKpvbk',
    appId: '1:535106210480:web:ec937e84f399cad8a18975',
    messagingSenderId: '535106210480',
    projectId: 'android-db188',
    authDomain: 'android-db188.firebaseapp.com',
    storageBucket: 'android-db188.firebasestorage.app',
    measurementId: 'G-1V6Z6LB4ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNMRCnKL8Q9RUgxnS10mYF0_69aNw3dM',
    appId: '1:535106210480:android:51b24b9bcd852365a18975',
    messagingSenderId: '535106210480',
    projectId: 'android-db188',
    storageBucket: 'android-db188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Ek1xOqsAnAL7m3xwgCw2eGdVb9SvCJc',
    appId: '1:535106210480:ios:12213b25e56c4fb3a18975',
    messagingSenderId: '535106210480',
    projectId: 'android-db188',
    storageBucket: 'android-db188.firebasestorage.app',
    iosBundleId: 'noithat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Ek1xOqsAnAL7m3xwgCw2eGdVb9SvCJc',
    appId: '1:535106210480:ios:208756c9f5440f60a18975',
    messagingSenderId: '535106210480',
    projectId: 'android-db188',
    storageBucket: 'android-db188.firebasestorage.app',
    iosBundleId: 'web',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbOMWZU0RKoLrYcOxgDHpnBQ5qSfKpvbk',
    appId: '1:535106210480:web:9cddab7edc189712a18975',
    messagingSenderId: '535106210480',
    projectId: 'android-db188',
    authDomain: 'android-db188.firebaseapp.com',
    storageBucket: 'android-db188.firebasestorage.app',
    measurementId: 'G-3FL8FQ60XK',
  );
}
